# This is a basic workflow to upload files
# from GitHub to server via GitHub Actions

name: Everest academy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event
  # but only for the specific branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action

    # The type of runner that the job will run on 
    # (depends on server but usually this value works)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
          # Checkout a specific branch
          ref: main
          
      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build
      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          remote-protocol: ftp
          # Credentials for SFTP access to server using GitHub secrets
          server: ftp.w3techsite.com
          username: admin@academy.w3developers.com.np
          password: FS0He}rIWxgB
         # Path for specific folder on server for files deployment
          local-dir: ./dist/
